In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import fetch_california_housing

In [3]:
data = fetch_california_housing()
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
housing_df = pd.DataFrame(data['data'],columns=data['feature_names'])
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [5]:
target = pd.Series(data['target'])
target.head()

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
dtype: float64

In [6]:
# Set a random seed

np.random.seed(42)

# Set X and y

X = housing_df
y = target

# Do test and train split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Import and fit model
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(n_estimators=1000)
regr.fit(X_train,y_train)

regr.score(X_test,y_test)

0.8083212359139857

In [7]:
# Set a random seed

np.random.seed(42)

# Set X and y

X = housing_df
y = target

# Do test and train split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Import and fit model
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(n_estimators=100)
regr.fit(X_train,y_train)

#Gather predict probability

y_preds = regr.predict(X_test)

In [8]:
# Apply mean absolute error

from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test,y_preds)

0.32659871732073664

In [9]:
# Apply mean squared error

from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_preds)

0.2534678520824551

In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor()

np.random.seed(42)
cv_max_error = cross_val_score(rgr, X, y, cv=5, scoring="max_error")
cv_max_error

array([-3.4962   , -3.46027  , -3.5359999, -3.7027698, -3.7521   ])

In [14]:
print(f'The cross-validated max-error is: {np.mean(cv_max_error):.2f}')

The cross-validated max-error is: -3.59


# Explained variance

In [16]:
np.random.seed(42)
cv_exp_var = cross_val_score(regr, X, y, cv=5, scoring="explained_variance")
cv_exp_var

array([0.69509228, 0.70290344, 0.74328315, 0.61823016, 0.71705081])

# R2

In [18]:
np.random.seed(42)
cv_r2 = cross_val_score(regr, X, y, cv=5)
cv_r2

array([0.51682388, 0.70279716, 0.74197717, 0.61638204, 0.68243183])

# Mean absolute error

In [21]:
np.random.seed(42)
cv_mae = cross_val_score(regr, X, y, cv=5, scoring='neg_mean_absolute_error')
cv_mae

array([-0.54256026, -0.40902123, -0.43706982, -0.46918522, -0.47318856])

In [22]:
np.mean(cv_mae)

-0.46620501732073655

# Using functions for evaluating score

In [29]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Set the seed

np.random.seed(42)

# Set up X, y

X, y

# Set up train test splity
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Create Model

regr = RandomForestRegressor()

# Fit Model

regr.fit(X_train, y_train)

# Make a Prediction

y_preds = regr.predict(X_test)

# Evaluate Model Scores

print(f'Coefficient of Determination is: {r2_score(y_test,y_preds):.2f}')
print(f'Mean Absolute Error is: {mean_absolute_error(y_test,y_preds):.2f}')
print(f'Mean Squared Error is: {mean_squared_error(y_test,y_preds):.2f}')

Coefficient of Determination is: 0.81
Mean Absolute Error is: 0.33
Mean Squared Error is: 0.25
