In this notebook, we're going to cover some of the most concepts of using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting infomation from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorsFlow (or TPUs)
* Exercises to try for yourself

# Intro to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.10.1


## Creating tensors with tf.constant()

In [17]:
# Create a scaler with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scaler.ndim

0

In [6]:
# Create a vector
vector = tf.constant([1,2,3,4,5])
vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [8]:
# Check the number of dimension of our vector
vector.ndim

1

In [10]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
# Check the number of dimension of our matrix
matrix.ndim

2

In [14]:
# Create another matrix but specificaly the dtype
another_matrix = tf.constant([[10.,7.],
                             [7.,10.],
                             [2.,3.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 2.,  3.]], dtype=float16)>

In [16]:
# Check our number of dimensions
another_matrix.ndim

2

In [19]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,4],
                      [5,6,7,8]],
                     [[9,10,11,12],
                     [13,14,15,16]]])
tensor

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])>

In [20]:
# Check dimension of tensor
tensor.ndim

3

What we've created so far:
* Scaler: Single number
* Vector: A number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of number (where n can be any number)

## Creating tensors with tf.Variable

In [21]:
tf.Variable()

tensorflow.python.ops.variables.Variable

In [22]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [24]:
# Let's try to change one of the elements in our changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [25]:
# How about we try .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [26]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [28]:
# Let's try the same on our unchangeable_tensoabsr
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑**Note:** Rarely do we need to decide where to use tf.constant or tf.Variable for creating tensors, as they are made autoamtically. But if in doubt, use tf.constant and change it later if needed

## Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [32]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [33]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

## Shuffle the order of elements in a tensor

In [36]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [44]:
shuffled = tf.random.shuffle(not_shuffled,seed=42)

In [45]:
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [10,  7],
        [ 2,  5]])>)

## Experiment with seed

In [48]:
t1 = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
t2 = tf.constant([[9,3,7],
                 [4,5,1],
                 [4,5,6]])

In [58]:
tf.random.set_seed(42)
tf.random.shuffle(t1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])>

In [93]:
tf.random.set_seed(42)
tf.random.shuffle(t2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 1],
       [4, 5, 6],
       [9, 3, 7]])>

## Create a tensor with all ones

In [94]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

## Create a tensor with all zeros

In [95]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU

In [96]:
# You can also turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # Create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensors
# y = tf.constant (vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [99]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)

In [100]:
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)