In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray

In [3]:
a1 = np.array([1,2,3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array ([[1,2.0,3.3],
                [4,5,6.5]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a1.ndim

1

In [10]:
a2.ndim

2

In [13]:
a3 = np.array ([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],
      [[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [18]:
sample_array = np.array([1,2,3])

In [19]:
sample_array

array([1, 2, 3])

In [21]:
ones = np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
zeros = np.zeros((2,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,10,2)

In [26]:
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0,10, size=(3,5))

In [28]:
random_array

array([[0, 0, 5, 9, 5],
       [1, 7, 5, 2, 8],
       [4, 0, 2, 0, 3]])

In [29]:
np.random.random((5,3))

array([[0.36769148, 0.30348962, 0.77135128],
       [0.74037574, 0.5637501 , 0.4194063 ],
       [0.11957387, 0.72626217, 0.48140938],
       [0.96257191, 0.91223691, 0.44511626],
       [0.7569782 , 0.05900007, 0.69640791]])

In [36]:
# Pseudo-random numbers
np.random.seed(4)
random_array_4 = np.random.randint(0,10, size=(3,5))
random_array_4

array([[7, 5, 1, 8, 7],
       [8, 2, 9, 7, 7],
       [7, 9, 8, 4, 2]])

## Viewing arrays and matrices

In [37]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [38]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [39]:
a4

array([[[[6, 4, 3, 0, 7],
         [5, 5, 9, 6, 6],
         [8, 2, 5, 8, 1],
         [2, 7, 0, 8, 3]],

        [[1, 0, 3, 2, 3],
         [2, 9, 2, 1, 0],
         [1, 9, 9, 0, 7],
         [2, 6, 3, 7, 8]],

        [[2, 6, 7, 7, 9],
         [2, 7, 5, 3, 0],
         [5, 4, 3, 8, 9],
         [5, 8, 6, 7, 0]]],


       [[[4, 6, 8, 4, 8],
         [1, 9, 5, 4, 2],
         [3, 4, 7, 6, 6],
         [8, 0, 3, 5, 6]],

        [[1, 1, 6, 0, 8],
         [7, 5, 7, 6, 8],
         [4, 4, 0, 7, 2],
         [1, 8, 8, 1, 3]],

        [[1, 3, 6, 7, 4],
         [0, 7, 3, 7, 9],
         [6, 6, 9, 3, 2],
         [7, 6, 7, 9, 4]]]])

In [40]:
a4[1][1][0]

array([1, 1, 6, 0, 8])

## 4. Manipulating and comaparing arrays

### Arithmetic

In [42]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a2.shape

(2, 3)

In [46]:
a3.shape

(2, 3, 3)

In [47]:
a2 = np.array([a2])

In [48]:
a2

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.5]]])

In [49]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (1,2,3) (2,3,3) 

### Aggregation

Aggregation = performing the same operation on a number of things

In [50]:
list1 = [1,2,3]

In [51]:
type(list1)

list

In [52]:
a1

array([1, 2, 3])

In [53]:
sum(a1)

6

In [54]:
np.sum(a1)

6

In [55]:
# Use Python's methods on Python datatypes and use Numpy's methods on NumPy Arrays

In [56]:
# Create a massive NumPy array
massive_array = np.random.random(10000)

In [57]:
massive_array

array([0.41903403, 0.90242186, 0.97961626, ..., 0.02534416, 0.33194721,
       0.89642837])

In [58]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

849 µs ± 7.73 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.42 µs ± 76.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [59]:
a2

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.5]]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [61]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

## Dot Product

In [62]:
np.random.seed(0)

matl = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [64]:
matl

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [65]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [71]:
np.dot(matl.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [67]:
mat1.T

NameError: name 'mat1' is not defined

In [68]:
matl

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [69]:
matl

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [70]:
mat.T

NameError: name 'mat' is not defined

## Nut butter sales

In [73]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [77]:
#Create weekly sales
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon","Tues","Wed","Thur","Fri"],
                            columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [79]:
#Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [84]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=["Price"],
                             columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [85]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [87]:
# Shapes aren't aligned
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [88]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [90]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [91]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [92]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [93]:
daily_sales

Mon  Tues  Wed  Thur  Fri
Price  240   138  458   232  142

In [97]:
weekly_sales["Total ($)"] = daily_sales.T

In [98]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total $  Total ($)
Mon              12             15              0      240        240
Tues              3              3              7      138        138
Wed               9             19             18      458        458
Thur              4              6             12      232        232
Fri               1              6              7      142        142

In [100]:
weekly_sales.drop(columns=["Total $"],axis=1)

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon              12             15              0        240
Tues              3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142

In [101]:
random_array

array([[0, 0, 5, 9, 5],
       [1, 7, 5, 2, 8],
       [4, 0, 2, 0, 3]])

In [106]:
np.sort(random_array)

array([[0, 0, 5, 5, 9],
       [1, 2, 5, 7, 8],
       [0, 0, 2, 3, 4]])

## Practical Example - Images!

<img src="panda.png"/>

In [108]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("panda.png")

In [110]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="car-photo.png">

In [112]:
car = imread("car-photo.png")

<img src="dog-photo.png">

In [113]:
dog = imread("dog-photo.png")