# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array_dim1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
array_dim2 = np.array([[1,2,3],
                       [4,5,6]])


# Create a 3-dimensional Numpy array using np.array()
array_dim3 = np.array([[[1,2,3],
                        [4,5,6]],
                       [[7,8,9],
                       [10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_dim1.shape, array_dim1.ndim, array_dim1.dtype, array_dim1.size, type(array_dim1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
array_dim2.shape, array_dim2.ndim, array_dim2.dtype, array_dim2.size, type(array_dim2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
# Attributes of 2-dimensional array
array_dim3.shape, array_dim3.ndim, array_dim3.dtype, array_dim3.size, type(array_dim3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(array_dim2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[2, 8],
       [7, 5],
       [1, 6],
       [6, 7],
       [9, 6],
       [1, 7],
       [1, 9]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.43734937, 0.36403202, 0.36164276, 0.77586115, 0.74999825],
       [0.74868957, 0.52659745, 0.76477199, 0.44096597, 0.33344382],
       [0.83395876, 0.77422561, 0.46898449, 0.82699234, 0.12302723]])

In [16]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0,10, (4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array2 = np.random.randint(1,10,(3,7))
random_array2

# Find the unique numbers in the array you just created
np.unique(random_array2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Find the 0'th index of the latest array you created
random_array2[0]

array([9, 1, 3, 7, 4, 9, 3])

In [21]:
# Get the first 2 rows of latest array you created
random_array2[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [28]:
# Get the first 2 values of the first 2 rows of the latest array
random_array2[:2,:2]

array([[7, 8],
       [4, 2]])

In [8]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arrayX = np.random.randint(0,10,(3,5))
ones_arrayX = np.ones((3,5))

random_arrayX


array([[1, 8, 8, 0, 8],
       [9, 4, 1, 0, 8],
       [7, 4, 1, 6, 0]])

In [13]:
# Add the two arrays together
combo_x = ones_arrayX + random_arrayX

In [10]:
# Create another array of ones of shape (5, 3)
ones_arrayX.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Try add the array of ones and the other most recent array together
ones_arrayX.T + combo_x

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [16]:
# Create another array of ones of shape (3, 5)
combo_y = combo_x.T + ones_arrayX.T

In [17]:
# Subtract the new array of ones from the other most recent array
combo_y - ones_arrayX.T

array([[ 2., 10.,  8.],
       [ 9.,  5.,  5.],
       [ 9.,  2.,  2.],
       [ 1.,  1.,  7.],
       [ 9.,  9.,  1.]])

In [20]:
# Multiply the ones array with the latest array
new_array = combo_y * ones_arrayX.T

In [21]:
# Take the latest array to the power of 2 using '**'
new_array ** 2

array([[  9., 121.,  81.],
       [100.,  36.,  36.],
       [100.,   9.,   9.],
       [  4.,   4.,  64.],
       [100., 100.,   4.]])

In [22]:
# Do the same thing with np.square()
np.square(new_array)

array([[  9., 121.,  81.],
       [100.,  36.,  36.],
       [100.,   9.,   9.],
       [  4.,   4.,  64.],
       [100., 100.,   4.]])

In [23]:
# Find the mean of the latest array using np.mean()
np.mean(new_array)

6.333333333333333

In [24]:
# Find the maximum of the latest array using np.max()
np.max(new_array)

11.0

In [25]:
# Find the minimum of the latest array using np.min()
np.min(new_array)

2.0

In [26]:
# Find the standard deviation of the latest array
np.std(new_array)

3.4189017079888226

In [27]:
# Find the variance of the latest array
np.var(new_array)

11.68888888888889

In [29]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = new_array.reshape(3,5,1)

In [30]:
# Transpose the latest array
reshaped_array.T

array([[[ 3.,  6.,  2.],
        [11., 10.,  8.],
        [ 9.,  3., 10.],
        [10.,  3., 10.],
        [ 6.,  2.,  2.]]])

What does the transpose do?

In [31]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_array_1 = np.random.randint(0,10,(3,3))
rand_array_2 = np.random.randint(0,10,(3,2))

In [32]:
# Perform a dot product on the two newest arrays you created
rand_array_1.dot(rand_array_2)

array([[ 35,  76],
       [ 53,  84],
       [ 71, 106]])

In [33]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_array_3 = np.random.randint(0,10,(4,3))
rand_array_4 = np.random.randint(0,10,(4,3))

In [34]:
# Perform a dot product on the two newest arrays you created
rand_array_3.dot(rand_array_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [35]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand_array_3.dot(rand_array_4.T)

array([[ 40,  84,  22, 104],
       [  4,  47,   6,  42],
       [ 72, 128,  32, 160],
       [ 67, 110,  15, 120]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [36]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_array_5 = np.random.randint(0,10,(3,3))
rand_array_6 = np.random.randint(0,10,(3,3))

In [37]:
# Compare the two arrays with '>'
rand_array_5 > rand_array_6

array([[False,  True,  True],
       [False,  True, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [38]:
# Compare the two arrays with '>='
rand_array_5 >= rand_array_6

array([[False,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

In [39]:
# Find which elements of the first array are greater than 7
rand_array_5 > 7

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [40]:
# Which parts of each array are equal? (try using '==')
rand_array_5 == rand_array_6

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [41]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_array_5)

array([[0, 6, 8],
       [0, 1, 7],
       [2, 3, 4]])

In [42]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_array_5)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int64)

In [45]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_array_5, axis=0)

array([2, 1, 0], dtype=int64)

In [46]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_array_6, axis=0)

array([2, 2, 1], dtype=int64)

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [51]:
# Create an array of normally distributed random numbers
np.random.randn(5,5)

array([[ 0.49454475,  0.90230136,  1.45864071,  1.37721512, -1.22172863],
       [ 1.37439829, -0.13400732,  0.582886  , -0.07860201, -0.32800506],
       [-1.44183656, -0.44451316, -0.88649355,  1.77008351, -0.07710688],
       [ 0.75021497,  0.74297061,  0.21942006,  0.5349076 ,  0.19165816],
       [ 0.21571759, -1.89011836, -0.41942172,  0.87822459,  0.44851065]])

In [47]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.